import { Inter } from 'next/font/google'
import './globals.css'
import '@fontsource/angkor';
import '@fontsource/poppins';
import Navbar from '@/components/Nav'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Golden Slice Pizzeria',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
